const RESPONSE_CODES = {
	SUCCESS: 'SUCCESS',
	BAD_PARAMETERS: 'BAD_PARAMETERS',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	JWT_ERROR: 'JWT_ERROR',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
};

module.exports = RESPONSE_CODES;
